version: "3"

services:
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus_tcs
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_tcs
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka_tcs
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      #      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      #      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      #      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      #      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

      # Настройки топиков и репликации
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3                  # Количество партиций - 3

      # Параметры хранения логов
      - KAFKA_CFG_LOG_RETENTION_HOURS=24            # Хранение логов - 1 день
      - KAFKA_CFG_LOG_SEGMENT_BYTES=104857600       # Максимальный размер сегмента лога - 100 МБ
    depends_on:
      - zookeeper
