version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_securityDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: securityDB
      POSTGRES_USER: yakdanol
      POSTGRES_PASSWORD: yakdanol
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_securityCache
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
