version: '3.8'

services:
# PostgreSQL
  # БД пользователей для анализа трафика
  users-db:
    image: postgres:16
    container_name: postgres_usersDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: usersDB
      POSTGRES_USER: yakdanol
      POSTGRES_PASSWORD: yakdanol
    ports:
      - "5432:5432"
    volumes:
      - db-users-data:/var/lib/postgresql/data

  # БД для отчетов analysis‐микросервиса
  reports_analysis_db:
    image: postgres:16
    container_name: postgres_reports_analysisDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: reportsDB
      POSTGRES_USER: yakdanol
      POSTGRES_PASSWORD: yakdanol
    ports:
      - "5434:5432"
    volumes:
      - reports-analysis-db-data:/var/lib/postgresql/data

  # БД для отчетов security‐микросервиса
  reports_security_db:
    image: postgres:16
    container_name: postgres_reports_securityDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: reportsDB
      POSTGRES_USER: yakdanol
      POSTGRES_PASSWORD: yakdanol
    ports:
      - "5433:5432"
    volumes:
      - reports-security-db-data:/var/lib/postgresql/data

  # БД пользователей для анализа трафика
  users-notification-db:
    image: postgres:16
    container_name: postgres_notification_usersDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: notification_usersDB
      POSTGRES_USER: yakdanol
      POSTGRES_PASSWORD: yakdanol
    ports:
      - "5435:5432"
    volumes:
      - db-notification-users-data:/var/lib/postgresql/data

#Redis

  # Redis для analysis‐микросервиса
  redis_analysis:
    image: redis:latest
    container_name: redis_analysisCache
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6380:6379"
    volumes:
      - redis-analysis-data:/data

  # Redis для security‐микросервиса
  redis_security:
    image: redis:latest
    container_name: redis_securityCache
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-security-data:/data

volumes:
  db-users-data:
    driver: local
  db-notification-users-data:
    driver: local
  reports-security-db-data:
    driver: local
  reports-analysis-db-data:
    driver: local
  redis-analysis-data:
    driver: local
  redis-security-data:
    driver: local