server:
  port: 8083

traffic-security:
  general-config:
    data-source: FILE
    pool-size: 6                  # Кол-во потоков многопоточной работы
  file-config:
    directory: "/data"        # Путь к директории размещения файлов для анализа
  kafka-consumer-configs:
    bootstrap-servers: "localhost:9092"
#    topic-name: "traffic.capture.WN-0001"
    group-id: "analysis-service"
    offset-reset: "latest"
    auto-commit: "false"
    session-timeout-ms: 30000      # Время ответа на heartbeat пакет
    heartbeat-interval-ms: 10000   # Интервал между отправками heartbeat сообщений
    linger-ms: 100                 # Время ожидания (в миллисекундах) перед отправкой batch сообщений
    batch-size: 10                 #  Максимальное кол-во полученных за раз данных
    retries: 3                     # Кол-во повторных попыток запросов к Kafka при ошибках и сбоях
    retry-delay-ms: 1000           # Пауза между retry (мс)
    callback-timeout-s: 1          # Таймаут ожидания ответа от Kafka (сек)

logging:
  level:
    root: INFO
  file:
    name: traffic-security.log

spring:
  datasource:
    url: jdbc:h2:mem:securitydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
