server:
  port: 8081

traffic-capture:
  user: "WN-0001"
  system: "Windows 10"
  interface-name: "RZ616 Wi-Fi 6E 160MHz" # Имя сетевого интерфейса для захвата трафика
  log-directory: "ns-traffic-capture-service\\logs" # Директория для сохранения лог-файлов микросервиса
  log-format: "json" # Формат логирования: json, xml, text
  filter: "host 192.168.1.8" # BPF фильтр (pcap-filter(7)) для захвата пакетов
  # "host 192.168.1.8" / "(src host *) or (dst host *)"
  processing-pool-size: 2 # Количество потоков для обработки пакетов
  queue-size: 100 # Размер очереди для буферизации пакетов
  console-logging: true # Логирование данных в консоль

logging:
  level:
    root: INFO
  file:
    name: traffic-capture.log

spring:
  main:
    allow-bean-definition-overriding: true
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
