global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ns-traffic-capture-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081'] # localhost:9090 или localhost:8081 или host.docker.internal:8081

# http://localhost:8081/actuator/prometheus или http://localhost:9090